import { criarMensagensOperacao } from "../../../constants/criar.mensagem.operacao";
import type { Usuario } from "../type/usuario";

const ENTITY_NAME = "Usuário";

export const USUARIO = {
  ENTITY: ENTITY_NAME,

  ALIAS: "usuario",

  DADOS_INICIAIS: {
    idUsuario: "",
    codUsuario: "",
    nomeUsuario: "",
    email: "",
    senha: "",
    confirmSenha: "",
    tipo: "",
    idCidade: "",
    nomeCidade: "",
    idade: "",
    idAluno: "",
    codAluno: "",
    nomeAluno: "",
    idProfessor: "",
    codProfessor: "",
    nomeProfessor: "",
    foto: "",
    contentType: "",
  },

  FIELDS: {
    ID: "idUsuario",
    CODIGO_USUARIO: "codUsuario",
    NOME_USUARIO: "nomeUsuario",
    EMAIL: "email",
    SENHA: "senha",
    CONFIRM_SENHA: "confirmSenha",
    TIPO_USUARIO: "tipo",
    ID_CIDADE: "idCidade",
    NOME_CIDADE: "nomeCidade",
    IDADE: "idade",
    ID_ALUNO: "idAluno",
    COD_ALUNO: "codAluno",
    NOME_ALUNO: "nomeAluno",
    ID_PROFESSOR: "idProfessor",
    COD_PROFESSOR: "codProfessor",
    NOME_PROFESSOR: "nomeProfessor",
    FOTO: "foto",
    CONTENT_TYPE: "contentType",
    STATUS: "ativo",
  } as const,

  LABEL: {
    CODIGO_USUARIO: "Código do Usuário",
    NOME_USUARIO: "Nome",
    EMAIL: "Email",
    SENHA: "Senha",
    CONFIRM_SENHA: "Confirme a Senha",
    TIPO_USUARIO: "Tipo",
    ID_CIDADE: "Código da Cidade",
    NOME_CIDADE: "Nome da Cidade",
    IDADE: "Idade",
    ID_ALUNO: "Código do Aluno",
    COD_ALUNO: "Código do Aluno",
    NOME_ALUNO: "Nome do Aluno",
    ID_PROFESSOR: "Código do Professor",
    COD_PROFESSOR: "Código do Professor",
    NOME_PROFESSOR: "Nome do Professor",
    ACAO: "Ação",
    STATUS: "Situação",
  },

  TITULO: {
    LISTAR: `Lista de ${ENTITY_NAME}s`,
    CRIAR: `Novo ${ENTITY_NAME}`,
    ATUALIZAR: `Atualizar ${ENTITY_NAME}`,
    EXCLUIR: `Excluir ${ENTITY_NAME}`,
    CONSULTAR: `Consultar ${ENTITY_NAME}`,
  },

  INPUT_ERROR: {
    ID: {
      BLANK: `O código de identificação do ${ENTITY_NAME} deve ser informado`,
      VALID: `Informe um código de identificação válido para o ${ENTITY_NAME}`,
    },
    CODIGO_USUARIO: {
      BLANK: `O código do ${ENTITY_NAME} deve ser informado`,
      VALID: `Informe um código válido para o ${ENTITY_NAME}`,
      MAX_LEN: `O código do ${ENTITY_NAME} deve conter no máximo 20 caracteres`,
      MIN_LEN: `O código do ${ENTITY_NAME} deve conter no mínimo 6 caracteres`,
      STRING: `O código do ${ENTITY_NAME} dever ser um texto `,
    },
    NOME_USUARIO: {
      BLANK: `O nome  de ${ENTITY_NAME} deve ser informado`,
      VALID: `O nome  de ${ENTITY_NAME} não está digitado corretamente`,
      MAX_LEN: `O nome  de ${ENTITY_NAME} deve conter no máximo 100 caracteres`,
      MIN_LEN: `O nome  de ${ENTITY_NAME} deve conter no mínimo 6 caracteres`,
      STRING: `O nome  de ${ENTITY_NAME} dever ser um texto `,
    },
    EMAIL: {
      BLANK: `O e-mail  de ${ENTITY_NAME} deve ser informado`,
      VALID: `O e-mail  de ${ENTITY_NAME} não está digitado corretamente`,
      MAX_LEN: `O e-mail  de ${ENTITY_NAME} deve conter no máximo 100 caracteres`,
      MIN_LEN: `O e-mail  de ${ENTITY_NAME} deve conter no mínimo 6 caracteres`,
      STRING: `O e-mail  de ${ENTITY_NAME} dever ser um texto `,
    },
    SENHA: {
      BLANK: `A senha  de ${ENTITY_NAME} deve ser informada`,
      VALID: `A senha  de ${ENTITY_NAME} não está digitado corretamente`,
      MAX_LEN: `A senha  de ${ENTITY_NAME} deve conter no máximo 20 caracteres`,
      MIN_LEN: `A senha  de ${ENTITY_NAME} deve conter no mínimo 6 caracteres`,
      STRING: `A senha  de ${ENTITY_NAME} dever ser um texto `,
    },
    CONFIRM_SENHA: {
      BLANK: `A senha  de ${ENTITY_NAME} deve ser informada`,
      VALID: `As senhas  de ${ENTITY_NAME} não estão iguais`,
      MAX_LEN: `A senha  de ${ENTITY_NAME} deve conter no máximo 20 caracteres`,
      MIN_LEN: `A senha  de ${ENTITY_NAME} deve conter no mínimo 6 caracteres`,
      STRING: `A senha  de ${ENTITY_NAME} dever ser um texto `,
    },
    TIPO_USUARIO: {
      BLANK: `O tipo  de ${ENTITY_NAME} deve ser informado`,
      VALID: `O tipo  de ${ENTITY_NAME} não está digitado corretamente`,
      MAX_LEN: `O tipo  de ${ENTITY_NAME} deve conter no máximo 1 caracteres`,
      MIN_LEN: `O tipo  de ${ENTITY_NAME} deve conter no mínimo 1 caracteres`,
      STRING: `O tipo  de ${ENTITY_NAME} dever ser um texto `,
    },
    ID_CIDADE: {
      BLANK: `O código da cidade  de ${ENTITY_NAME} deve ser informado`,
      VALID: `O código da cidade  de ${ENTITY_NAME} não está digitado corretamente`,
      STRING: `O código da cidade  de ${ENTITY_NAME} dever ser um texto `,
    },
    NOME_CIDADE: {
      BLANK: `O nome da cidade de ${ENTITY_NAME} deve ser informado`,
      VALID: `O nome da cidade de ${ENTITY_NAME} não está digitado corretamente`,
      MAX_LEN: `O nome da cidade de ${ENTITY_NAME} deve conter no máximo 100 caracteres`,
      MIN_LEN: `O nome da cidade de ${ENTITY_NAME} deve conter no mínimo 6 caracteres`,
      STRING: `O nome da cidade de ${ENTITY_NAME} dever ser um texto `,
    },
    IDADE: {
      BLANK: `A idade  de ${ENTITY_NAME} deve ser informado`,
      VALID: `A idade  de ${ENTITY_NAME} não está digitado corretamente`,
      MAX_LEN: `A idade  de ${ENTITY_NAME} deve conter no máximo 2 caracteres`,
      MIN_LEN: `A idade  de ${ENTITY_NAME} deve conter no mínimo 0 caracteres`,
    },
    ID_ALUNO: {
      BLANK: `O identificador de ${ENTITY_NAME} deve ser informado`,
      VALID: `O identificador de ${ENTITY_NAME} não está digitado corretamente`,
      STRING: `O identificador de ${ENTITY_NAME} dever ser um texto `,
    },
    COD_ALUNO: {
      BLANK: `O código de ${ENTITY_NAME} deve ser informado`,
      VALID: `O código de ${ENTITY_NAME} não está digitado corretamente`,
      MAX_LEN: `O código de ${ENTITY_NAME} deve conter no máximo 5 caracteres`,
      MIN_LEN: `O código de ${ENTITY_NAME} deve conter no mínimo 5 caracteres`,

      STRING: `O código do aluno  de ${ENTITY_NAME} dever ser um texto `,
    },
    NOME_ALUNO: {
      BLANK: `O  nome de ${ENTITY_NAME} deve ser informado`,
      VALID: `O  nome de ${ENTITY_NAME} não está digitado corretamente`,
      MAX_LEN: `O  nome de ${ENTITY_NAME} deve conter no máximo 100 caracteres`,
      MIN_LEN: `O  nome de ${ENTITY_NAME} deve conter no mínimo 6 caracteres`,
      STRING: `O  nome de ${ENTITY_NAME} dever ser um texto `,
    },
    ID_PROFESSOR: {
      BLANK: `O identificador de ${ENTITY_NAME} deve ser informado`,
      VALID: `O identificador de ${ENTITY_NAME} não está digitado corretamente`,
      STRING: `O identificador de ${ENTITY_NAME} dever ser um texto `,
    },
    COD_PROFESSOR: {
      BLANK: `O código de ${ENTITY_NAME} deve ser informado`,
      VALID: `O código de ${ENTITY_NAME} não está digitado corretamente`,
      MAX_LEN: `O código de ${ENTITY_NAME} deve conter no máximo 5 caracteres`,
      MIN_LEN: `O código de ${ENTITY_NAME} deve conter no mínimo 5 caracteres`,
      STRING: `O código de ${ENTITY_NAME} dever ser um texto `,
    },
    NOME_PROFESSOR: {
      BLANK: `O nome  de ${ENTITY_NAME} deve ser informado`,
      VALID: `O nome  de ${ENTITY_NAME} não está digitado corretamente`,
      MAX_LEN: `O nome  de ${ENTITY_NAME} deve conter no máximo 100 caracteres`,
      MIN_LEN: `O nome  de ${ENTITY_NAME} deve conter no mínimo 6 caracteres`,
      STRING: `O nome  de ${ENTITY_NAME} dever ser um texto `,
    },
  },

  OPERACAO: criarMensagensOperacao(ENTITY_NAME),
};

export const fieldsUsuario: (keyof Usuario)[] = [
  USUARIO.FIELDS.ID,
  USUARIO.FIELDS.CODIGO_USUARIO,
  USUARIO.FIELDS.NOME_USUARIO,
  USUARIO.FIELDS.EMAIL,
  USUARIO.FIELDS.SENHA,
  USUARIO.FIELDS.CONFIRM_SENHA,
  USUARIO.FIELDS.TIPO_USUARIO,
  USUARIO.FIELDS.ID_CIDADE,
  USUARIO.FIELDS.NOME_CIDADE,
  USUARIO.FIELDS.IDADE,
  USUARIO.FIELDS.ID_ALUNO,
  USUARIO.FIELDS.COD_ALUNO,
  USUARIO.FIELDS.NOME_ALUNO,
  USUARIO.FIELDS.ID_PROFESSOR,
  USUARIO.FIELDS.COD_PROFESSOR,
  USUARIO.FIELDS.NOME_PROFESSOR,
];

export const mapaCampoParaMensagem: Partial<
  Record<keyof Usuario, keyof typeof USUARIO.INPUT_ERROR>
> = {
  idUsuario: "ID",
  codUsuario: "CODIGO_USUARIO",
  nomeUsuario: "NOME_USUARIO",
  email: "EMAIL",
  senha: "SENHA",
  confirmSenha: "CONFIRM_SENHA",
  tipo: "TIPO_USUARIO",
  idCidade: "ID_CIDADE",
  nomeCidade: "NOME_CIDADE",
  idade: "IDADE",
  idAluno: "ID_ALUNO",
  codAluno: "COD_ALUNO",
  nomeAluno: "NOME_ALUNO",
  idProfessor: "ID_PROFESSOR",
  codProfessor: "COD_PROFESSOR",
  nomeProfessor: "NOME_PROFESSOR",
};
